# Generated by Django 4.1.4 on 2022-12-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_goods_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='goods',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='market/images/%Y/%m/%d/'),
        ),
    ]
